### ISSUE TITLE
Relevant case study/review paper

### ISSUE THREAD

**Issue by sdimi** [liaoyuhua/LLM4TS#1]
https://arxiv.org/abs/2309.06236

**Comment by liaoyuhua** [comment]
> https://arxiv.org/abs/2309.06236

Great share

**Comment by sdimi** [comment]
Thanks! Let me know if you are interested in adding it to the readme.

**Comment by liaoyuhua** [comment]
> Thanks! Let me know if you are interested in adding it to the readme.

Hi, work has been added!
