### ISSUE TITLE
No code implementation of LLM4TS

### ISSUE THREAD

**Issue by marcopeix** [liaoyuhua/LLM4TS#3]
There is no code provided for LLM4TS. I would love to experiment with LLM4TS, GPT4TS, or PromptCast, but there are only links to papers with no code implementation.

Is it possible to provide links to the code?

**Comment by liaoyuhua** [comment]
Hi, this repo accidentally has the same name as LLM4TS paper. Sounds like you want LLM4TS paper source code. Till now, there is not public implementation of LLM4TS paper. I'm doing some related work that you might be interested in. see https://github.com/liaoyuhua/llm4ts-pytorch
